/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GestionDonnee;

import javax.swing.*;
import java.sql.*;

/**
 *
 * @author DevJudeno
 */
public class ui_inscription extends javax.swing.JFrame {

    /**
     * Creates new form ui_inscription
     */
    public ui_inscription() {
        initComponents();
        setLocationRelativeTo(null);
        connecterBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextFieldNomComplet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AfficherPasword = new javax.swing.JCheckBox();
        ButtonConecter = new javax.swing.JButton();
        TextPassword = new javax.swing.JPasswordField();
        ButtonInscrire = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxRole = new javax.swing.JComboBox<>();
        TextFieldTelephone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Schadow BT", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 4, 88));
        jLabel2.setText("S'inscrire");

        jLabel3.setFont(new java.awt.Font("Schadow BT", 0, 20)); // NOI18N
        jLabel3.setText("Role");

        TextFieldNomComplet.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Schadow BT", 0, 20)); // NOI18N
        jLabel4.setText("Mot de passe");

        AfficherPasword.setText("Afficher mot de passe");
        AfficherPasword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherPaswordActionPerformed(evt);
            }
        });

        ButtonConecter.setBackground(new java.awt.Color(1, 4, 88));
        ButtonConecter.setFont(new java.awt.Font("Schadow BT", 1, 16)); // NOI18N
        ButtonConecter.setForeground(new java.awt.Color(255, 255, 255));
        ButtonConecter.setText("S'inscrire");
        ButtonConecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConecterActionPerformed(evt);
            }
        });

        TextPassword.setFont(new java.awt.Font("Schadow BT", 0, 15)); // NOI18N

        ButtonInscrire.setBackground(new java.awt.Color(249, 249, 249));
        ButtonInscrire.setForeground(new java.awt.Color(1, 4, 88));
        ButtonInscrire.setText("Connecter");
        ButtonInscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInscrireActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Schadow BT", 0, 20)); // NOI18N
        jLabel5.setText("Nom Complet de l'utilisateur");

        ComboBoxRole.setFont(new java.awt.Font("Schadow BT", 0, 15)); // NOI18N
        ComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrateur", "Secretaire" }));
        ComboBoxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxRoleActionPerformed(evt);
            }
        });

        TextFieldTelephone.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Schadow BT", 0, 20)); // NOI18N
        jLabel6.setText("Telephone");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TextFieldTelephone)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(ButtonConecter, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(ButtonInscrire, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(138, 138, 138))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AfficherPasword, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                            .addComponent(TextPassword)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldNomComplet)
                        .addComponent(ComboBoxRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)))
                .addGap(0, 22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(179, 179, 179))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldNomComplet, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(AfficherPasword)
                .addGap(38, 38, 38)
                .addComponent(ButtonConecter, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonInscrire)
                .addGap(17, 17, 17))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\NetBeansProjects\\netbeansBoockraft\\icon\\BOOKCRAFT.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AfficherPaswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherPaswordActionPerformed
        // TODO add your handling code here:
        if (AfficherPasword.isSelected()) {
            TextPassword.setEchoChar((char) 0);
        } else {
            TextPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_AfficherPaswordActionPerformed

    private void ButtonConecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConecterActionPerformed
        // TODO add your handling code here:
        inscriptionBD();
        dispose();
        new class_Connecter().setVisible(true);
    }//GEN-LAST:event_ButtonConecterActionPerformed

    private void ButtonInscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInscrireActionPerformed
        new class_Connecter().setVisible(true);
        // new ui_Inscription().setVisible(true);
    }//GEN-LAST:event_ButtonInscrireActionPerformed

    private void ComboBoxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxRoleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ui_inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ui_inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ui_inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ui_inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ui_inscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AfficherPasword;
    private javax.swing.JButton ButtonConecter;
    private javax.swing.JButton ButtonInscrire;
    private javax.swing.JComboBox<String> ComboBoxRole;
    private javax.swing.JTextField TextFieldNomComplet;
    private javax.swing.JTextField TextFieldTelephone;
    private javax.swing.JPasswordField TextPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    //connexion BD
    public static String chaineConnexion = "jdbc:mysql://localhost/bd_BooCraft_UIApp";
    public static String hote = "root";
    public static String password = "";
    public static Connection conn = null;
    public static Statement stat = null;
    public static ResultSet rs = null;
    private JTextField textFieldTelephone;

    private void connecterBD()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); // Chaje driver MySQL
            conn = DriverManager.getConnection(chaineConnexion, hote, password);
            System.out.println("✅ Connexion réussie !");
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("❌ Erreur de connexion à la base de données: " + e.getMessage());
        }
    }

    public void inscriptionBD()
    {
        String nomComplet = TextFieldNomComplet.getText();
        String RoleUser = (String)ComboBoxRole.getSelectedItem();
        String telephone = TextFieldTelephone.getText();
        String passwordUser = new String(TextPassword.getPassword());

        if (!nomComplet.isEmpty() && !RoleUser.isEmpty() && !telephone.isEmpty() && !passwordUser.isEmpty()) {
            String Inscrit = "INSERT INTO UserName(nomComplet, RoleUser, telephone, passwordUser) VALUES (?, ?, ?, ?)";

            try (Connection conn = DriverManager.getConnection(chaineConnexion, hote, password);
                 PreparedStatement pst = conn.prepareStatement(Inscrit)) {

                pst.setString(1, nomComplet);
                pst.setString(2, RoleUser);
                pst.setString(3, telephone);
                pst.setString(4, passwordUser);

                int rowsAffected = pst.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Inscription réussie!", "Succès", JOptionPane.INFORMATION_MESSAGE);
                    TextFieldNomComplet.setText("");
                    TextFieldTelephone.setText("");
                    TextPassword.setText("");
                    ComboBoxRole.setSelectedIndex(0);
                    //cardLayout.show(mainPanel, "connexion");
                }
            } catch (SQLException ex) {
                System.out.println("❌ Erreur SQL : " + ex.getMessage());
                JOptionPane.showMessageDialog(this, "Erreur SQL : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs", "Erreur", JOptionPane.ERROR_MESSAGE);
        }

    }
}
